### PR TITLE
ENH: construct dataset using tensorflow graph

### PR DESCRIPTION
**Pull request by Leengit**
This constructs the input dataset using tensorflow graph constructs.  In theory, this allows tensorflow to optimize the order of the steps so as to maximize performance.  However, it is about 4 times slower than the implementation that it replaces.  I am putting it here for soliciting feedback, and in case it proves useful in the future to have this documented.  

**See comments below as to why this is now a pull request that can be merged.**

### CODE REVIEW

**Comment by cooperlab** [comment]
@Leengit the new code is slower than the original prototype? The TF profiler may be helpful here in narrowing down the cause here. The prototype contains mostly TF functions so I would be interested to know the difference.

**Comment by Leengit** [comment]
The timing is back to the original timing now that I have set `num_parallel_calls = tf.data.experimental.AUTOTUNE`.  This pull request is now worthy of accepting.

**Comment by Leengit** [comment]
In summary, the new code:

1. Can start with multiple `(slide, magnification)` pairs; i.e., multiple slides and/or multiple magnifications per slide. 
1. For each `(slide, magnification)` pair, computes read parameters (e.g., svs image `level`, `factor`) and adds them to the dataset.
1. Desired tile sizes (width, height, and overaps) and chunk factors (for number of tiles wide and high) are added to the dataset.  User can substitute in an alternative approach for this step; e.g., specify different tile sizes for different slides or different magnifications.
1. Chunk positions are computed and added to the dataset.  (Previously, chunk positions were computed first and then a constant tuple  `(slide, magnification, level, factor, ...)` was added to every chunk.)
1. The step of computing the tile positions and sizes within a chunk is combined with the step that reads in the chunk and splits the image into tiles
1. Functions given as arguments to `dataset.map(...)` no longer modify their inputs.
1. Steps that previously needed to be followed by `_expand_tensors` now have that functionality within the steps.

**Review by cooperlab — APPROVED** [review]
It's good to mix possibly multiple slides into a single dataset, but we may want to filter the results by slide so they can be saved separately, so just make sure the slide metadata is captured in the outputs.

**Comment by Leengit** [comment]
> It's good to mix possibly multiple slides into a single dataset, but we may want to filter the results by slide so they can be saved separately, so just make sure the slide metadata is captured in the outputs.

Agreed.  It's there.

**Pull request merged**
