### PR TITLE
ENH: TensorFlow graph handles tile-selection mask

### PR DESCRIPTION
**Pull request by Leengit**
A mask file can be supplied to determine which tiles from a whole slide image should be retained for learning or inference.  This mask is first [resampled](https://itk.org/ITKExamples/src/Filtering/ImageGrid/ResampleAnImage/Documentation.html) if necessary so that it has exactly one pixel for each and every tile that could be selected for subsequent processing.  A non-zero value for a pixel indicates that the corresponding tile should be kept.

Also,
    ENH: Stop using zarr-jpeg package, which is problematic in our context
    STYLE: Use snake_case for Python function and variable names

### CODE REVIEW

**Comment by cooperlab** [comment]
Reason for using itk instead of tf.image.resize? It may not matter if this is an early step or a small amount of data.

**Comment by Leengit** [comment]
> Reason for using itk instead of tf.image.resize? It may not matter if this is an early step or a small amount of data.

Good point.  I just tried the `tf.resize` function there.  It appears to work for my test case of a single whole-slide image with a mask -- though conceptually I need to understand what it means to have tensorflow graph functionality inside a `py_` function, in this case inside `py_compute_resampled_mask`.

I could move all the code to inside the `tf_compute_resampled_mask` function.  That should give us the full power of the tensorflow graph.  (I am thinking that I would need to replace `itk.imread` there with `tf` functionality too.)  However, I am thinking to delay that to another pull request.  It took me quite a while to get to code that wouldn't choke tensorflow, so I'd like to check this in as a base to launch future efforts from.

**Comment by cooperlab** [comment]
I agree there is probably no advantage to putting tf functions inside a py_ function. At that point you have already paid any penalty from calling python.

Wherever possible we should use tf functions to help tf optimize the input pipeline. A future PR is fine. We have plenty of examples for how to read image buffers using tf functions.

**Comment by Leengit** [comment]
The force-push just now bumps the tensorflow_reader version number to 1.0.7.

**Pull request merged**
